kind: pipeline
type: kubernetes
name: scramblr_web

steps:
  - name: build
    commands:
      - yarn
      - yarn test
      - yarn build
      - mc config host add minio https://minio.herrengtltd.com $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
      - mc rm -r --force minio/scramblr/assets
      - mc cp -r build/ minio/scramblr/assets
