version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: node:13
    steps:
      - checkout
      - run: yarn
      - run: yarn build
workflows:
  build-and-test:
    jobs:
      - build-and-test
