version: 2.1
jobs:
  test:
    docker:
      - image: node:13
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: yarn
      - run: yarn test
  build:
    docker:
      - image: node:13
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: yarn build
  deploy:
    docker:
      - image: minio/mc
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: ls build
      - run: mc
