version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
            - yarn build
            - mc config host add minio https://minio.herrengtltd.com $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
            - mc rm -r --force minio/scramblr/assets
            - mc cp -r build/ minio/scramblr/assets
workflows:
  build-and-test:
    jobs:
      - build-and-test
